### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by francisco-rente** [francisco-rente/FEUP-PRI#1]
- [x] Search repositories for datasets;
- [x] Select convenient data subsets;
- [x] Assess the authority of the data source and data quality;
- [x] Perform exploratory data analysis;
- [x] Prepare and document a data processing pipeline;
- [x] Characterize the datasets, identifying and describing some of their properties;
- [ ] Identify the conceptual model for the data domain;
- [ ] Identify follow-up information needs in the data domain.
