### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by francisco-rente** [francisco-rente/FEUP-PRI#2]
- [ ] Choose the information retrieval tool (Solr, Elasticsearch, Lucene, Terrier, …);
- [ ] Analyze the documents and identify their indexable components;
- [ ] Use the selected tool to build the indexes;
- [ ] Use the selected tool to configure and execute the queries;
- [ ] Demonstrate the indexing and retrieval processes;
- [ ] Manually evaluate the returned results;
- [ ] Evaluate the results obtained for the defined information needs.
